### ISSUE TITLE
功能不正常啊，无法启用啊

### ISSUE THREAD

**Issue by charles-liming** [cleviry/xiaoyi_crack#10]

**Comment by charles-liming** [comment]
![image](https://user-images.githubusercontent.com/34326414/146127935-974e2d49-28e3-4a4a-819b-de226be556fe.png)

1、

**Comment by charles-liming** [comment]
perfect

**Comment by charles-liming** [comment]
现在我用鼠标不能选文字，一旦鼠标做选文字的操作，就会弹框没有登录，请登录

**Comment by cleviry** [comment]
是否有装过其他版本插件
是否退出账号
是否清空浏览器缓存
描述具体点  起码截个图

**Comment by charles-liming** [comment]
本来想浮现，回家后再试，问题没了

**Comment by charles-liming** [comment]
能加个微信吗，感觉你好厉害，想认识下

**Comment by charles-liming** [comment]
![image](https://user-images.githubusercontent.com/34326414/146485075-ba816178-9cea-4b80-8416-f45424278d70.png)

**Comment by cleviry** [comment]
现在还会出现问题吗？重新下载试下
