### ISSUE TITLE
下载用了一阵，然后突然不能用了

### ISSUE THREAD

**Issue by Pepperzxy** [cleviry/xiaoyi_crack#13]
我下载用了一阵，但是过一阵就不灵了，我下载还了deepl插件和沙拉查词插件，我清除了浏览器的浏览数据，该插件我也没有登陆账号，您看看还有什么解决方案吗？两个图片显示插件里有错误。
<img width="467" alt="截屏2021-12-27 上午10 15 38" src="https://user-images.githubusercontent.com/95515571/147427864-5ede4c49-962a-4aa5-9610-51482c420b34.png">
<img width="714" alt="截屏2021-12-27 上午10 15 48" src="https://user-images.githubusercontent.com/95515571/147427875-06b6e662-4f0c-41da-a4cc-8cd374590ca2.png">

**Comment by cleviry** [comment]
建议删除插件，重新git下载试一下

**Comment by Aheadboy** [comment]
我也碰到了，不能用。没有报错，没有翻译

**Comment by monstermaster9** [comment]
会被直接更新到最新版本

**Comment by bemorechill** [comment]
同，几天后突然不能用了，有Content Security Policy directive: *connect-src 'self' 报错。移除后重新下载加载无效，仍有相同报错qwq
