### ISSUE TITLE
不能用了吗？

### ISSUE THREAD

**Issue by lanmoxia** [cleviry/xiaoyi_crack#17]
![image](https://user-images.githubusercontent.com/86523141/160267080-a23b7e73-8d23-48c3-b9b4-f60cc7bb5a2d.png)

**Comment by cleviry** [comment]
额 访问github有时要挂代理   或者国内用下面的命令
```bash
git clone https://github.91chi.fun/https://github.com/cleviry/xiaoyi_crack.git
```

**Comment by lanmoxia** [comment]
嗯 你说完可以了

**Comment by lanmoxia** [comment]
艺灵？
