### ISSUE TITLE
可能已失效

### ISSUE THREAD

**Issue by RoyTrue** [cleviry/xiaoyi_crack#18]
Chrome浏览器，任意网页，点击插件，右下角只会弹出图标，并不会进行翻译。希望作者能够更新一下

**Comment by cleviry** [comment]
> Chrome浏览器，任意网页，点击插件，右下角只会弹出图标，并不会进行翻译。希望作者能够更新一下
说下具体版本号

**Comment by RoyTrue** [comment]
十分抱歉，您回复之后，我再次测试，发现现在能够正常使用了，打扰您了，抱歉抱歉。
chrome版本：101.0.4951.67
彩云小译版本：1.0.3
