### ISSUE TITLE
无法启动网页全文翻译 - Chrome 浏览器

### ISSUE THREAD

**Issue by ktaming** [cleviry/xiaoyi_crack#6]
您好，我发现该软件无法全文翻译。
状况如下：
打开英文网站后，点击小译图标/右键网页空白处点击启动彩云小译，都能够正常呼出右下角的四个悬浮图标，并且网页显示
![image](https://user-images.githubusercontent.com/20518966/136682531-07b9c555-5962-45cf-b71e-020a1f6329e5.png)
字样。

但网页内容的翻译，不会出现。
如图：
![image](https://user-images.githubusercontent.com/20518966/136682543-b898c130-cd68-405c-b726-05448d01aa29.png)
![image](https://user-images.githubusercontent.com/20518966/136682551-2d2d96dc-0455-4cc4-a6c7-ade014882bf2.png)

浏览器：版本 94.0.4606.71（正式版本） 
网络环境：加拿大温哥华Telus

**Comment by cleviry** [comment]
你好，请提供下网址

**Comment by ktaming** [comment]
您好。

我没有安装其他版本彩云小译。
确实登录了彩云小译账号，退出账号后就正常了，谢谢您！

本issue关闭。
