### ISSUE TITLE
建议增加关闭提示文字的选项

### ISSUE THREAD

**Issue by ktaming** [cleviry/xiaoyi_crack#7]
您好。
感谢您的工作！

一个小建议，您可以考虑在后续版本中添加“关闭“小译火力全开FREE”字样提示”，每次都有这个提示，还是比较困扰的…

如果能“设置一次，永久不再提示”就好了。

谢谢您！

**Comment by cleviry** [comment]
会加的

**Comment by ktaming** [comment]
嘤嘤嘤，好像没加？
